E=/home/user/Git/persistent-pancake/cur/build/classes/java/main:\
/home/user/Git/persistent-pancake/cur/build/classes/groovy/main:\
/home/user/Git/persistent-pancake/cur/build/resources/main:\
/home/user/.m2/repository/com/squareup/okhttp3/okhttp/4.10.0/okhttp-4.10.0.jar:\
/home/user/.m2/repository/com/codahale/metrics/metrics-healthchecks/3.0.2/metrics-healthchecks-3.0.2.jar:\
/home/user/.m2/repository/com/codahale/metrics/metrics-core/3.0.2/metrics-core-3.0.2.jar:\
/home/user/.m2/repository/org/jooq/jool/0.9.14/jool-0.9.14.jar:\
/home/user/.m2/repository/org/hashids/hashids/1.0.3/hashids-1.0.3.jar:\
/home/user/.m2/repository/com/typesafe/config/1.4.2/config-1.4.2.jar:\
/home/user/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar:\
/home/user/.m2/repository/io/undertow/undertow-servlet/2.3.4.Final/undertow-servlet-2.3.4.Final.jar:\
/home/user/.m2/repository/org/apache/commons/commons-lang3/3.3/commons-lang3-3.3.jar:\
/home/user/.m2/repository/net/java/dev/jna/jna/4.0.0/jna-4.0.0.jar:\
/home/user/.m2/repository/io/undertow/undertow-core/2.3.4.Final/undertow-core-2.3.4.Final.jar:\
/home/user/.m2/repository/me/friwi/jcefmaven/105.3.36/jcefmaven-105.3.36.jar:\
/home/user/.m2/repository/io/reactivex/rxjava3/rxjava/3.1.0/rxjava-3.1.0.jar:\
/home/user/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar:\
/home/user/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:\
/home/user/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar:\
/home/user/.m2/repository/org/jdeferred/v2/jdeferred-core/2.0.0/jdeferred-core-2.0.0.jar:\
/home/user/.m2/repository/tripleo/buffers/buffers-v1/0.0.3/buffers-v1-0.0.3.jar:\
/home/user/.m2/repository/tripleo/util/range/range-v1/0.0.3b/range-v1-0.0.3b.jar:\
/home/user/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.annotation/2.2.200/org.eclipse.jdt.annotation-2.2.200.jar:\
/home/user/.m2/repository/com/squareup/okio/okio-jvm/3.0.0/okio-jvm-3.0.0.jar:\
/home/user/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.jar:\
/home/user/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.31/kotlin-stdlib-jdk7-1.5.31.jar:\
/home/user/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.6.20/kotlin-stdlib-1.6.20.jar:\
/home/user/.m2/repository/org/jetbrains/annotations/16.0.2/annotations-16.0.2.jar:\
/home/user/.m2/repository/com/github/spotbugs/spotbugs-annotations/4.0.1/spotbugs-annotations-4.0.1.jar:\
/home/user/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:\
/home/user/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar:\
/home/user/.m2/repository/com/google/guava/guava/30.0-jre/guava-30.0-jre.jar:\
/home/user/.m2/repository/org/easymock/easymock/5.1.0/easymock-5.1.0.jar:\
/home/user/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:\
/home/user/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar:\
/home/user/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:\
/home/user/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.14.2/jackson-annotations-2.14.2.jar:\
/home/user/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar:\
/home/user/.m2/repository/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar:\
/home/user/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:\
/home/user/.m2/repository/me/friwi/jcef-api/jcef-0cdd84c+cef-105.3.36+g88e0038+chromium-105.0.5195.102/jcef-api-jcef-0cdd84c+cef-105.3.36+g88e0038+chromium-105.0.5195.102.jar:\
/home/user/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:\
/home/user/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:\
/home/user/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:\
/home/user/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:\
/home/user/.m2/repository/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar:\
/home/user/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar:\
/home/user/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:\
/home/user/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar:\
/home/user/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:\
/home/user/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.6.20/kotlin-stdlib-common-1.6.20.jar:\
/home/user/.m2/repository/org/jboss/threads/jboss-threads/3.5.0.Final/jboss-threads-3.5.0.Final.jar:\
/home/user/.m2/repository/org/jboss/xnio/xnio-api/3.8.8.Final/xnio-api-3.8.8.Final.jar:\
/home/user/.m2/repository/org/wildfly/client/wildfly-client-config/1.0.1.Final/wildfly-client-config-1.0.1.Final.jar:\
/home/user/.m2/repository/org/jboss/logging/jboss-logging/3.4.3.Final/jboss-logging-3.4.3.Final.jar:\
/home/user/.m2/repository/me/friwi/jogl-all/v2.4.0-rc-20210111/jogl-all-v2.4.0-rc-20210111.jar:\
/home/user/.m2/repository/me/friwi/gluegen-rt/v2.4.0-rc-20210111/gluegen-rt-v2.4.0-rc-20210111.jar:\
/home/user/.m2/repository/org/wildfly/common/wildfly-common/1.5.4.Final/wildfly-common-1.5.4.Final.jar:\
/home/user/Git/persistent-pancake/cur/build/classes/java/test

