/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "elijah-v1-fluffy-umbrella"


//src
//src-cef
include("src-mal")
include("src-undertow")

include("src-cef")//:tripleo.elijah:fluffy-cef')
//include(':tripleo.elijah:fluffy-mal')
//include(':tripleo.elijah:fluffy-undertow')


//include(':elijah-util')
//include(':dlog')
//include(':tripleo.small')
//include(':elijah-ek')

//include(':elijah-core-api')

//include(':tripleo.elijah.stateful')
////include(':tripleo.elijah.stateful-processor')

//include(':elijah-nextgen-outputstatement')
//include(':tripleo.elijah.core')
//include(':elijah-equilibrium-probe')
//include(':elijah-stage-eva')
//include(':elijah-stage-cross')
//include(':elijah-stage-deduce')
//include(':elijah-stage-genc')

//include(':elijah-equilibrium-probe')

////include(':annotation-user')
////include(':annotation-processing')
//include(':tripleo.elijah.reactive')

//project(":tripleo.elijah.stateful").projectDir = file('elijah-stateful')
////project(":tripleo.elijah.stateful-processor").projectDir = file('elijah-stateful-processor')
//project(":tripleo.elijah.core").projectDir = file('elijah-core')
//project(":tripleo.small").projectDir = file('tripleo-small')
//project(":tripleo.elijah.reactive").projectDir = file('tripleo-reactive')

